/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author WINDOWS
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cmbAutos = new javax.swing.JComboBox<>();
        cmbModo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Copa Loca Racing");
        jLabel1.setToolTipText("");

        jButton1.setText("Iniciar Carrera");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Manual de Usuario");

        cmbAutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "auto_rojo", "deportivo_azul", "deportivo_rojo", "formula_1", "formula_2", "vocho" }));
        cmbAutos.addActionListener(this::cmbAutosActionPerformed);

        cmbModo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Jugador", " ", "2 Jugadores" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(cmbAutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(cmbModo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbAutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(jButton2)
                .addGap(29, 29, 29)
                .addComponent(cmbModo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // BLOQUE 2: Va DENTRO del evento del botón Iniciar Carrera
        try {
            // 1. Obtenemos el auto que eligió el usuario en el ComboBox
            String eleccionJ1 = cmbAutos.getSelectedItem().toString();

            // 2. Creamos la lista exacta con los nombres de tus archivos
            java.util.ArrayList<String> disponibles = new java.util.ArrayList<>();
            disponibles.add("auto_rojo");
            disponibles.add("deportivo_azul");
            disponibles.add("deportivo_rojo");
            disponibles.add("formula_1");
            disponibles.add("formula_2");
            disponibles.add("vocho");

            // 3. Quitamos el que eligió el J1 para que no se repita
            disponibles.remove(eleccionJ1);

            // 4. Revolvemos los 5 que quedan
            java.util.Collections.shuffle(disponibles);

            // 5. Asignamos los dos primeros de la lista revuelta al J2 y a la CPU
            String eleccionJ2 = disponibles.get(0);
            String eleccionCPU = disponibles.get(1);

            // 6. Fabricamos los objetos para J1 y J2 usando el método de arriba
            modelo.Vehiculo autoJ1 = fabricarVehiculo(eleccionJ1);
            modelo.Vehiculo autoJ2 = fabricarVehiculo(eleccionJ2);
            
            // 7. Abrimos la pista. NOTA: Le pasamos también el nombre del auto de la CPU

            // Obtenemos si eligió 1 o 2 jugadores
            boolean esUnJugador = cmbModo.getSelectedItem().toString().equals("1 Jugador");

            // ... (El resto de tu código de selección y barajado de autos se queda igual) ...
            
            // ACTUALIZA LA LÍNEA DONDE ABRES LA PISTA para enviarle el modo de juego al final
            vista.PistaCarrera pista = new vista.PistaCarrera(autoJ1, autoJ2, "Medio", eleccionCPU, esUnJugador);
            pista.setVisible(true);
            this.dispose(); // Cierra el menú
            
        } catch (Exception e) { // Uso obligatorio del try-catch
            javax.swing.JOptionPane.showMessageDialog(this, "Falla de motor: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbAutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAutos;
    private javax.swing.JComboBox<String> cmbModo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
    // BLOQUE 1: Pon esto al final de MenuPrincipal.java (antes de la última llave '}')
    private modelo.Vehiculo fabricarVehiculo(String nombre) {
        switch(nombre) {
            case "auto_rojo": return new modelo.AutoDeportivo(nombre); // Usa la clase de Saúl[cite: 7]
            case "deportivo_azul": return new modelo.AutoDeportivo(nombre); // Usa la clase de Saúl[cite: 7]
            case "deportivo_rojo": return new modelo.AutoDeportivo(nombre); // Usa la clase de Saúl[cite: 7]
            case "formula_1": return new modelo.Formula1(nombre); // Usa la clase de Saúl[cite: 4]
            case "formula_2": return new modelo.Formula1(nombre); // Usa la clase de Saúl[cite: 4]
            case "vocho": return new modelo.Camioneta(nombre); // El vocho será la Camioneta (lento pero seguro)[cite: 8]
            default: return new modelo.AutoDeportivo("Generico"); // Clase por defecto[cite: 7]
        }
    }
}
